from __future__ import annotations

import base64
from io import BytesIO
from urllib.parse import quote

from .typing import FileLike


def _svg_data_url(title: str, subtitle: str, accent: str = "#d4af37") -> str:
    svg = f"""
    <svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
      <rect width="1024" height="1024" fill="#0a0f18" />
      <rect x="64" y="64" width="896" height="896" rx="36" fill="#111827" stroke="{accent}" stroke-width="6" />
      <text x="512" y="430" fill="#f3e5b1" font-size="54" font-family="Arial, sans-serif" text-anchor="middle">{title}</text>
      <text x="512" y="520" fill="#d1d5db" font-size="30" font-family="Arial, sans-serif" text-anchor="middle">{subtitle}</text>
      <text x="512" y="610" fill="#9ca3af" font-size="24" font-family="Arial, sans-serif" text-anchor="middle">WorkStation Core mock asset</text>
    </svg>
    """.strip()
    return f"data:image/svg+xml;charset=utf-8,{quote(svg)}"


def _glb_data_url(mesh_id: str) -> str:
    payload = f"Mock GLB placeholder for {mesh_id}".encode("utf-8")
    encoded = base64.b64encode(payload).decode("ascii")
    return f"data:model/gltf-binary;base64,{encoded}"


def _obj_data_url(mesh_id: str) -> str:
    obj_text = "\n".join(
        [
            f"# Mock OBJ for {mesh_id}",
            "o WorkStationCoreMock",
            "v 0.0 0.0 0.0",
            "v 1.0 0.0 0.0",
            "v 0.0 1.0 0.0",
            "f 1 2 3",
        ]
    )
    return f"data:text/plain;charset=utf-8,{quote(obj_text)}"


def _safe_float(value: object, default: float) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _mesh_stats(base_triangles: int, params: dict) -> dict:
    smooth = _safe_float(params.get("smooth"), 0.5)
    decimate = _safe_float(params.get("decimate"), 0.5)
    thickness = _safe_float(params.get("thickness"), 0.5)

    refined_triangles = int(max(400, base_triangles + (smooth * 900) - (decimate * 1200) + (thickness * 350)))
    width = round(0.7 + (thickness * 0.5), 2)
    height = round(1.0 + (smooth * 0.35), 2)
    return {
        "triangles": refined_triangles,
        "width": width,
        "height": height,
    }


def file_to_data_url(file_obj: FileLike | None) -> str | None:
    if file_obj is None:
        return None

    content = file_obj.read()
    if not content:
        return None

    mime_type = getattr(file_obj, "mimetype", None) or "application/octet-stream"
    encoded = base64.b64encode(content).decode("ascii")
    return f"data:{mime_type};base64,{encoded}"


def build_ai_image_response(scope, prompt: str, style: str, aspect: str) -> dict:
    subtitle = f"{scope.product} | {style} | {aspect}"
    return {
        "ok": True,
        "imageUrl": _svg_data_url(prompt[:36] or "Concept", subtitle),
        "note": "Mock AI image generated by WorkStation Core.",
        "scope": scope.to_dict(),
    }


def build_first_mesh_response(scope, species: str, source_image: str | None) -> dict:
    placeholder_source = source_image or _svg_data_url(
        species[:36] or "Source Image",
        f"{scope.project} | {scope.workspace}",
    )
    return {
        "ok": True,
        "glbUrl": _glb_data_url("pending-mesh"),
        "objUrl": _obj_data_url("pending-mesh"),
        "sourceImage": placeholder_source,
        "species": species,
        "stats": _mesh_stats(6400, {}),
        "note": "Mock first-pass mesh created by WorkStation Core.",
    }


def build_refined_mesh_response(existing: dict, params: dict) -> dict:
    mesh_id = existing["meshId"]
    refined = dict(existing)
    refined["ok"] = True
    refined["glbUrl"] = _glb_data_url(mesh_id)
    refined["objUrl"] = _obj_data_url(mesh_id)
    refined["params"] = params
    refined["stats"] = _mesh_stats(existing.get("stats", {}).get("triangles", 6400), params)
    refined["note"] = "Mock refined mesh created by WorkStation Core."
    return refined


def build_generate_model_response(scope, model_type: str, preview_image: str | None) -> dict:
    preview = preview_image or _svg_data_url(
        model_type[:36] or "Generated Model",
        f"{scope.product} | {scope.workspace}",
        accent="#58b9ff",
    )
    return {
        "ok": True,
        "modelType": model_type,
        "previewImage": preview,
        "note": "Mock generate-model response from WorkStation Core.",
        "scope": scope.to_dict(),
    }